[package]
name = "rust-template"
version = "0.0.1"
edition = "2024"
authors = ["You <user@email.com>"]
description = "Opinionated Rust template for new projects"
license = "MIT"

[dependencies]
tracing = "0.1.41"
serde_json = "1.0"
anyhow = "1.0.98"
tracing-subscriber = "0.3"
